import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Toaster } from "@/components/ui/sonner"
import { dbConnect } from "@/lib/mongo";

export const metadata = {
  title: "Server Actions",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
   
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar/>
            <main>{children}</main>
        </ThemeProvider>
        <Toaster richColors position="bottom-right"/>
      </body>
    </html>
  );
}
